---
- hosts:   kvm_host
  ansible_become: yes
  ansible_become_method: su
  ansible_become_user: root
  ansible_become_pass: galaxy
  remote_user: yagzhang
  vars:
    image_name: /mnt/tmpssd/rhel-guest-image-7.3-35.x86_64.qcow2
    instance_name: '{{ name }}'
    instance_dir: '/mnt/tmpssd/'
    tem_dir: /home/wangzezhi/ops/ansible/playbooks/templates
    tem_file: "{{ tem_dir }}/set_ip_tem.sh.j2"
    file_name: /tmp/set_ip.sh


  tasks:
  - name: just test virsh command 
    shell: virsh lsit
    tags: file

  tasks:
  - name: create the file set_ip.sh
    template: src=templates/set_ip_tem.sh.j2 dest={{ file_name }}
    tags: file

  - name: clone the instance
    command: virt-clone -o {{ image_name }} -n {{ instance_name }}  -f /{{ instance_dir }}/{{ instance_name }}.qcow2
    tags: clone

  - name: copy in the  file set_ip.sh
    shell: virt-copy-in -d {{ instance_name }} {{ file_name }} /opt/
    tags: file_copy_in

  - name: start the instance
    shell: virsh start {{ instance_name }}
    tags: start
