---
- hosts:   kvm_host
  vars:
    image_name: rhel66_1
    instance_name: '{{ name }}'
    instance_dir: '/mnt/tmpssd/'
    tem_dir: /home/wangzezhi/ops/ansible/playbooks/templates
    tem_file: "{{ tem_dir }}/set_ip_tem.sh.j2"
    file_name: /tmp/set_ip.sh
    hook_file: /tmp/request_tower_configuration.sh

  tasks:
  - name: just test virsh command 
    shell: virsh list
    become: true
    tags: test

  - name: create the file set_ip.sh
    template: src=../templates/set_ip_tem.sh.j2 dest={{ file_name }} owner=root group=root mode='0755'
    become: true
    tags: file

  - name: create the hook file
    template: src=../templates/request_tower_configuration.sh.j2  dest={{ hook_file }} owner=root group=root mode='0755'
    become: true
    tags: hookfile


  - name: clone the instance
    command: virt-clone -o {{ image_name }} -n {{ instance_name }}  -f {{ instance_dir }}{{ instance_name }}.qcow2
    become: true
    tags: clone

  - name: copy in the  file set_ip.sh
    shell: virt-copy-in -d {{ instance_name }} {{ file_name }} /opt/
    become: true
    tags: file_copy_in

  - name: copy in the  file request_tower_configuration.sh
    shell: virt-copy-in -d {{ instance_name }} {{ hook_file }} /opt/
    become: true
    tags: hook_file_copy_in

  - name: start the instance
    shell: virsh start {{ instance_name }}
    become: true
    tags: start
