---
- hosts: test_machine

  tasks:
    
  - name: change script runnbale
    delegate_to: localhost
    shell: cp templates/create_final_reuslts.sh.j2  /var/lib/awx/securityscan/create_final_reuslts.sh
    
  - name: Run the below script
    delegate_to: localhost
    command: sh /var/lib/awx/securityscan//create_final_reuslts.sh
